---
collections:
  - name: community.docker
  - name: ansible.posix
  - name: community.general
  - name: community.crypto
  - name: ansible.utils
# roles:
#   # Only include external roles if needed
#   - name: geerlingguy.docker
#     version: 6.1.0
