---
# Common packages to install on all systems
common_packages:
  - vim
  - htop
  - tmux
  - git
  - curl
  - wget
  - unzip
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - python3-pip
  - python3-setuptools
  - net-tools
  - iotop
  - dstat
  - sysstat
  - traceroute
  - tcpdump
  - rsync
  - acl

# System configuration
common_timezone: "{{ system.timezone | default('UTC') }}"
common_locale: "{{ system.locale | default('en_US.UTF-8') }}"
common_ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org

# Sysctl parameters for performance and security
common_sysctl_params:
  # Network performance
  net.core.somaxconn: 65535
  net.core.netdev_max_backlog: 5000
  net.ipv4.tcp_max_syn_backlog: 8192
  net.ipv4.tcp_slow_start_after_idle: 0
  net.ipv4.tcp_tw_reuse: 1
  net.ipv4.ip_local_port_range: "1024 65535"
  # File system
  fs.file-max: 2097152
  # VM settings for Docker/container hosts
  vm.swappiness: 10
  vm.dirty_ratio: 60
  vm.dirty_background_ratio: 2

# Unattended upgrades
common_unattended_upgrades_enabled: true
common_unattended_upgrade_origins:
  - "${distro_id}:${distro_codename}"
  - "${distro_id}:${distro_codename}-security"
  - "${distro_id}:${distro_codename}-updates"
common_unattended_upgrade_mail: "root@localhost"
common_unattended_upgrade_automatic_reboot: true
common_unattended_upgrade_automatic_reboot_time: "02:00"
