---
- name: Install auditd package
  ansible.builtin.apt:
    name: auditd
    state: present
    update_cache: true
  tags: [security, audit]

- name: Configure audit rules
  ansible.builtin.template:
    src: templates/auditd/audit.rules.j2
    dest: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: "0640"
  notify: Restart auditd
  tags: [security, audit]

- name: Configure auditd settings
  ansible.builtin.template:
    src: templates/auditd/auditd.conf.j2
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
    mode: "0640"
  notify: Restart auditd
  tags: [security, audit]

- name: Enable and start auditd service
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true
  tags: [security, audit]
