---
- name: Ensure Traefik network exists
  community.docker.docker_network:
    name: traefik-public
    driver: bridge
    state: present
  tags: [mailcow, integration]

- name: Connect Mailcow to Traefik network
  ansible.builtin.template:
    src: templates/docker-compose.override.yml.j2
    dest: "{{ mailcow_dest }}/docker-compose.override.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  tags: [mailcow, integration]
