---
- name: Create Docker volume backup script
  ansible.builtin.template:
    src: templates/docker_backup.sh.j2
    dest: "{{ backup_base_dir }}/scripts/docker_backup.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: "0750"
  tags: [backup, docker]

- name: Create Docker volume backup cleanup script
  ansible.builtin.template:
    src: templates/cleanup.sh.j2
    dest: "{{ backup_base_dir }}/scripts/docker_cleanup.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_group }}"
    mode: "0750"
  tags: [backup, docker, cleanup]

- name: Set up Docker volume backup cron job
  ansible.builtin.cron:
    name: "Docker volume backup"
    job: "{{ backup_base_dir }}/scripts/docker_backup.sh >> {{ backup_base_dir }}/logs/docker_backup.log 2>&1"
    minute: "{{ backup_schedule.docker_volumes.cron.split(' ')[0] }}"
    hour: "{{ backup_schedule.docker_volumes.cron.split(' ')[1] }}"
    day: "{{ backup_schedule.docker_volumes.cron.split(' ')[2] }}"
    month: "{{ backup_schedule.docker_volumes.cron.split(' ')[3] }}"
    weekday: "{{ backup_schedule.docker_volumes.cron.split(' ')[4] }}"
    user: "{{ backup_user }}"
  tags: [backup, docker, cron]

- name: Set up Docker volume backup cleanup cron job
  ansible.builtin.cron:
    name: "Docker volume backup cleanup"
    job: >-
      {{ backup_base_dir }}/scripts/docker_cleanup.sh docker {{ backup_schedule.docker_volumes.retention }} >>
      {{ backup_base_dir }}/logs/docker_cleanup.log 2>&1
    minute: "30"
    hour: "{{ backup_schedule.docker_volumes.cron.split(' ')[1] }}"
    day: "{{ backup_schedule.docker_volumes.cron.split(' ')[2] }}"
    month: "{{ backup_schedule.docker_volumes.cron.split(' ')[3] }}"
    weekday: "{{ backup_schedule.docker_volumes.cron.split(' ')[4] }}"
    user: "{{ backup_user }}"
  tags: [backup, docker, cron, cleanup]
