---
- name: Ensure required packages are installed
  ansible.builtin.apt:
    name:
      - docker-compose-plugin
      - python3-requests
    state: present
    update_cache: true
  become: true
  tags: [monitoring, prerequisites]

- name: Create base monitoring directory
  ansible.builtin.file:
    path: "{{ monitoring_base_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  tags: [monitoring, prerequisites]

- name: Create directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ monitoring_prometheus_config_dir }}"
    - "{{ monitoring_prometheus_config_dir }}/alerts"
    - "{{ monitoring_prometheus_data_dir }}"
    - "{{ monitoring_alertmanager_config_dir }}"
    - "{{ monitoring_alertmanager_data_dir }}"
    - "{{ monitoring_grafana_config_dir }}"
    - "{{ monitoring_grafana_config_dir }}/provisioning/datasources"
    - "{{ monitoring_grafana_config_dir }}/provisioning/dashboards"
    - "{{ monitoring_grafana_data_dir }}"
  tags: [monitoring, prerequisites]
