---
- name: Restart logging stack
  community.docker.docker_compose_v2:
    project_src: "{{ logging_base_dir }}"
    state: restarted
  become: true

- name: Restart filebeat
  community.docker.docker_compose_v2:
    project_src: "{{ logging_base_dir }}"
    services:
      - filebeat
    state: restarted
  become: true
