---
- name: Include packages tasks
  ansible.builtin.import_tasks: packages.yml
  tags: [common, packages]

- name: Include security tasks
  ansible.builtin.import_tasks: security.yml
  tags: [common, security]

- name: Configure timezone
  community.general.timezone:
    name: "{{ common_timezone }}"
  tags: [common, timezone]

- name: Configure locale
  community.general.locale_gen:
    name: "{{ common_locale }}"
    state: present
  tags: [common, locale]

- name: Configure kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-summitethic.conf
    reload: true
  with_dict: "{{ common_sysctl_params }}"
  tags: [common, sysctl]

- name: Include NTP tasks
  ansible.builtin.import_tasks: ntp.yml
  tags: [common, ntp]

- name: Include monitoring client tasks
  ansible.builtin.import_tasks: monitoring_client.yml
  tags: [common, monitoring]
