---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: [common, packages]

- name: Upgrade system packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
  tags: [common, packages]

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
  tags: [common, packages]

- name: Install Unattended-Upgrades package
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
  tags: [common, packages, security]

- name: Configure unattended upgrades
  ansible.builtin.template:
    src: templates/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"
  when: common_unattended_upgrades_enabled
  tags: [common, packages, security]

- name: Enable unattended upgrades
  ansible.builtin.template:
    src: templates/20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
  when: common_unattended_upgrades_enabled
  tags: [common, packages, security]
