---
- name: Check if ACME file exists
  ansible.builtin.stat:
    path: "{{ traefik_letsencrypt_dir }}/acme.json"
  register: acme_file
  tags: [traefik, configure]

- name: Create empty ACME file if it doesn't exist
  ansible.builtin.file:
    path: "{{ traefik_letsencrypt_dir }}/acme.json"
    state: touch
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  when: not acme_file.stat.exists
  tags: [traefik, configure]

- name: Configure log rotation for Traefik logs
  ansible.builtin.template:
    src: templates/traefik-logrotate.j2
    dest: /etc/logrotate.d/traefik
    owner: root
    group: root
    mode: "0644"
  tags: [traefik, configure, logging]

- name: Ensure Traefik logs are accessible
  ansible.builtin.file:
    path: "{{ traefik_log_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  tags: [traefik, configure, logging]
