---
- name: "Common Setup - Base System Configuration"
  hosts: all
  remote_user: "{{ ansible_user }}"
  gather_facts: true
  become: true
  vars_files:
    - "{{ inventory_dir }}/group_vars/vault.yml"
  tags:
    - common
  roles:
    - common

- name: "Security Setup - Hardening and Compliance"
  hosts: all
  remote_user: "{{ ansible_user }}"
  gather_facts: true
  become: true
  vars_files:
    - "{{ inventory_dir }}/group_vars/vault.yml"
  tags:
    - security
  roles:
    - security

- name: "Traefik Setup - Reverse Proxy Deployment"
  hosts: all
  remote_user: "{{ ansible_user }}"
  gather_facts: true
  become: true
  vars_files:
    - "{{ inventory_dir }}/group_vars/vault.yml"
  tags:
    - traefik
  roles:
    - traefik

- name: "Mailcow Setup - Mail Server Deployment"
  hosts: mail_servers
  remote_user: "{{ ansible_user }}"
  gather_facts: true
  become: true
  vars_files:
    - "{{ inventory_dir }}/group_vars/vault.yml"
  tags:
    - mailcow
  roles:
    - mailcow

- name: "Monitoring Setup - Observability Deployment"
  hosts: monitoring_servers
  remote_user: "{{ ansible_user }}"
  gather_facts: true
  become: true
  vars_files:
    - "{{ inventory_dir }}/group_vars/vault.yml"
  tags:
    - monitoring
  roles:
    - monitoring

- name: "Logging Setup - Centralized Logging Deployment"
  hosts: all
  remote_user: "{{ ansible_user }}"
  gather_facts: true
  become: true
  vars_files:
    - "{{ inventory_dir }}/group_vars/vault.yml"
  tags:
    - logging
  roles:
    - logging
