name: Molecule Tests

on:
  push:
    branches: [main, develop]
    paths:
      - "roles/**"
      - ".github/workflows/molecule-tests.yml"
  pull_request:
    branches: [main, develop]

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2204
          - debian11

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule molecule-docker pytest-testinfra docker

      - name: Install Galaxy requirements
        run: |
          ansible-galaxy collection install -r requirements.yml

      - name: Run Molecule tests
        run: |
          cd molecule/default
          MOLECULE_DISTRO=${{ matrix.distro }} molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
